"""add seller_fruit_id to sale table

Revision ID: 0dab944151d7
Revises: c3d02c043bf3
Create Date: 2025-09-28 01:20:07.967458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dab944151d7'
down_revision = 'c3d02c043bf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_fruit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sale_seller_fruit_id', 'seller_fruits', ['seller_fruit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_seller_fruit_id', type_='foreignkey')
        batch_op.drop_column('seller_fruit_id')
    # ### end Alembic commands ###
