"""add is_paid to salaries

Revision ID: 0f3ea6866bae
Revises: 195773a5eee0
Create Date: 2025-08-10 18:38:49.770377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f3ea6866bae'
down_revision = '195773a5eee0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salaries', schema=None) as batch_op:
        batch_op.drop_column('is_paid')

    # ### end Alembic commands ###
