"""add stock_name back to seller_fruits

Revision ID: 34c2c61fe0ec
Revises: 5b9a72d72d60
Create Date: 2025-09-17 15:57:32.581246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c2c61fe0ec'
down_revision = '5b9a72d72d60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seller_fruits', sa.Column('stock_name', sa.String(length=100), nullable=False, server_default='Unknown'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seller_fruits', 'stock_name')
    # ### end Alembic commands ###
