"""add expense_type and user_id to other_expenses

Revision ID: 4dcc233492e3
Revises: 1c0906afe75d
Create Date: 2025-08-10 11:39:34.447131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dcc233492e3'
down_revision = '1c0906afe75d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expense_type', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('fk_other_expenses_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('other_expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_other_expenses_user_id', type_='foreignkey')
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('user_id')
        batch_op.drop_column('expense_type')

    # ### end Alembic commands ###
