"""remove stock_name from seller_fruits

Revision ID: 5b9a72d72d60
Revises: ae1234567890
Create Date: 2025-09-16 16:56:07.529275

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '5b9a72d72d60'
down_revision = 'ae1234567890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support DROP COLUMN, so recreate table without stock_name
    op.execute('''
        CREATE TABLE seller_fruits_new (
            id INTEGER NOT NULL,
            fruit_name VARCHAR(50) NOT NULL,
            qty FLOAT NOT NULL,
            unit_price FLOAT NOT NULL,
            date DATE NOT NULL,
            amount FLOAT NOT NULL,
            created_at DATETIME,
            PRIMARY KEY (id)
        )
    ''')
    op.execute('INSERT INTO seller_fruits_new (id, fruit_name, qty, unit_price, date, amount, created_at) SELECT id, fruit_name, qty, unit_price, date, amount, created_at FROM seller_fruits')
    op.execute('DROP TABLE seller_fruits')
    op.execute('ALTER TABLE seller_fruits_new RENAME TO seller_fruits')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate table with stock_name
    op.execute('''
        CREATE TABLE seller_fruits_old (
            id INTEGER NOT NULL,
            stock_name VARCHAR(100) NOT NULL,
            fruit_name VARCHAR(50) NOT NULL,
            qty FLOAT NOT NULL,
            unit_price FLOAT NOT NULL,
            date DATE NOT NULL,
            amount FLOAT NOT NULL,
            created_at DATETIME,
            PRIMARY KEY (id)
        )
    ''')
    op.execute('INSERT INTO seller_fruits_old (id, fruit_name, qty, unit_price, date, amount, created_at, stock_name) SELECT id, fruit_name, qty, unit_price, date, amount, created_at, "" FROM seller_fruits')
    op.execute('DROP TABLE seller_fruits')
    op.execute('ALTER TABLE seller_fruits_old RENAME TO seller_fruits')
    # ### end Alembic commands ###
