"""add seller_fruit_id to sales table

Revision ID: 7975c8bf8683
Revises: b797594bec75
Create Date: 2025-09-27 11:43:10.225087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7975c8bf8683'
down_revision = 'b797594bec75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_fruit_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sales_seller_fruit_id', 'seller_fruits', ['seller_fruit_id'], ['id'])

    with op.batch_alter_table('seller_fruits', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.create_foreign_key('fk_seller_fruits_created_by', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seller_fruits', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('seller_fruit_id')
    # ### end Alembic commands ###
