"""Update Purchase model fields for frontend compatibility

Revision ID: 9e58423fdec7
Revises: c3ac9b3cc090
Create Date: 2025-08-08 14:54:14.638367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e58423fdec7'
down_revision = 'c3ac9b3cc090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('buyer_name', sa.String(length=100), nullable=False))
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('unit')
        batch_op.drop_column('employee_name')

    # ### end Alembic commands ###
