"""Add driver_expenses table

Revision ID: a2d7c2fde11d
Revises: ae195bda4282
Create Date: 2025-08-09 11:41:00.510572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2d7c2fde11d'
down_revision = 'ae195bda4282'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_email', sa.String(length=120), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_expenses')
    # ### end Alembic commands ###
