"""Add type and description to driver_expenses

Revision ID: a39e6364c901
Revises: a2d7c2fde11d
Create Date: 2025-08-09 11:55:25.239578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a39e6364c901'
down_revision = 'a2d7c2fde11d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('driver_expenses', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('type')

    # ### end Alembic commands ###
