"""add unit_price to sale table

Revision ID: add_unit_price_to_sale
Revises: drop_sale_table
Create Date: 2025-09-27 13:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_unit_price_to_sale'
down_revision = 'drop_sale_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_fruit_id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('fruit_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False, default=0),
    sa.Column('unit_price', sa.Float(), nullable=False, default=0.0),
    sa.Column('revenue', sa.Float(), nullable=False, default=0.0),
    sa.Column('sale_date', sa.DateTime(), nullable=True, default=sa.func.now()),
    sa.ForeignKeyConstraint(['seller_fruit_id'], ['seller_fruits.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    # ### end Alembic commands ###
