"""Add assignment_id to Sale model

Revision ID: ae195bda4282
Revises: 9e58423fdec7
Create Date: 2025-08-08 15:47:45.101117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae195bda4282'
down_revision = '9e58423fdec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('seller_email', sa.String(length=120), nullable=False),
    sa.Column('fruit_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assignment_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_sale_assignment_id', 'assignment', ['assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_assignment_id', type_='foreignkey')
        batch_op.drop_column('assignment_id')

    op.drop_table('assignment')
    # ### end Alembic commands ###
