"""add_created_by_to_seller_fruits

Revision ID: b797594bec75
Revises: fed639a7a380
Create Date: 2025-09-23 20:30:03.003095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b797594bec75'
down_revision = 'fed639a7a380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, we need to recreate the table with the new column
    op.execute('PRAGMA foreign_keys=OFF')

    # Create new table with the additional column
    op.execute('''
        CREATE TABLE seller_fruits_new (
            id INTEGER PRIMARY KEY,
            stock_name VARCHAR(100) NOT NULL,
            fruit_name VARCHAR(50) NOT NULL,
            qty FLOAT NOT NULL,
            unit_price FLOAT NOT NULL,
            date DATE NOT NULL,
            amount FLOAT NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            created_by INTEGER
        )
    ''')

    # Copy data from old table to new table
    op.execute('''
        INSERT INTO seller_fruits_new (id, stock_name, fruit_name, qty, unit_price, date, amount, created_at)
        SELECT id, stock_name, fruit_name, qty, unit_price, date, amount, created_at
        FROM seller_fruits
    ''')

    # Drop old table
    op.execute('DROP TABLE seller_fruits')

    # Rename new table
    op.execute('ALTER TABLE seller_fruits_new RENAME TO seller_fruits')

    # Re-enable foreign keys
    op.execute('PRAGMA foreign_keys=ON')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('PRAGMA foreign_keys=OFF')

    # Create new table without the created_by column
    op.execute('''
        CREATE TABLE seller_fruits_new (
            id INTEGER PRIMARY KEY,
            stock_name VARCHAR(100) NOT NULL,
            fruit_name VARCHAR(50) NOT NULL,
            qty FLOAT NOT NULL,
            unit_price FLOAT NOT NULL,
            date DATE NOT NULL,
            amount FLOAT NOT NULL,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ''')

    # Copy data from old table to new table (excluding created_by)
    op.execute('''
        INSERT INTO seller_fruits_new (id, stock_name, fruit_name, qty, unit_price, date, amount, created_at)
        SELECT id, stock_name, fruit_name, qty, unit_price, date, amount, created_at
        FROM seller_fruits
    ''')

    # Drop old table
    op.execute('DROP TABLE seller_fruits')

    # Rename new table
    op.execute('ALTER TABLE seller_fruits_new RENAME TO seller_fruits')

    # Re-enable foreign keys
    op.execute('PRAGMA foreign_keys=ON')
    # ### end Alembic commands ###
