"""Add purchase_price and purchase_date columns to inventory table

Revision ID: bc2bb5912ecf
Revises: 8489a15ac26c
Create Date: 2025-09-02 14:14:13.793480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc2bb5912ecf'
down_revision = '8489a15ac26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('purchase_date', sa.Date(), nullable=True))

    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_movement', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_column('purchase_date')
        batch_op.drop_column('purchase_price')

    # ### end Alembic commands ###
