"""Update sales table to match seller dashboard columns

Revision ID: c3d02c043bf3
Revises: add_unit_price_to_sale
Create Date: 2025-09-28 00:49:46.339013

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'c3d02c043bf3'
down_revision = 'add_unit_price_to_sale'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite to handle schema changes
    with op.batch_alter_table('sale', schema=None) as batch_op:
        # Delete existing sales data since structure is changing
        op.execute('DELETE FROM sale')
        batch_op.add_column(sa.Column('stock_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('fruit_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('qty', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date', sa.Date(), nullable=True))
        batch_op.drop_column('revenue')
        batch_op.drop_column('quantity')
        batch_op.drop_column('sale_date')
        batch_op.drop_column('seller_fruit_id')
        batch_op.drop_column('fruit_type')
        # Make columns NOT NULL after adding them
        batch_op.alter_column('stock_name', nullable=False)
        batch_op.alter_column('fruit_name', nullable=False)
        batch_op.alter_column('qty', nullable=False)
        batch_op.alter_column('amount', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False))
    op.add_column('sale', sa.Column('seller_fruit_id', sa.INTEGER(), nullable=False))
    op.add_column('sale', sa.Column('sale_date', sa.DATETIME(), nullable=True))
    op.add_column('sale', sa.Column('quantity', sa.INTEGER(), nullable=False))
    op.add_column('sale', sa.Column('revenue', sa.FLOAT(), nullable=False))
    op.create_foreign_key(None, 'sale', 'seller_fruits', ['seller_fruit_id'], ['id'])
    op.drop_column('sale', 'date')
    op.drop_column('sale', 'amount')
    op.drop_column('sale', 'qty')
    op.drop_column('sale', 'fruit_name')
    op.drop_column('sale', 'stock_name')
    op.create_table('it_event',
    sa.Column('id', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.Column('user_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('event_type', sa.VARCHAR(length=17), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('ip', sa.VARCHAR(length=45), nullable=True),
    sa.Column('device', sa.VARCHAR(length=255), nullable=True),
    sa.Column('resource', sa.VARCHAR(length=255), nullable=True),
    sa.Column('summary', sa.TEXT(), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=True),
    sa.Column('related_event_ids', sqlite.JSON(), nullable=True),
    sa.Column('server_logs', sa.TEXT(), nullable=True),
    sa.Column('stack_trace', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('receipts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('receipt_num', sa.VARCHAR(length=50), nullable=False),
    sa.Column('seller_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('seller_address', sa.VARCHAR(length=200), nullable=True),
    sa.Column('seller_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('buyer_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('buyer_contact', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('payment', sa.VARCHAR(length=50), nullable=True),
    sa.Column('items', sa.TEXT(), nullable=True),
    sa.Column('subtotal', sa.FLOAT(), nullable=True),
    sa.Column('discount', sa.FLOAT(), nullable=True),
    sa.Column('final_total', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receipt_num')
    )
    op.create_table('it_alert',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('event_ids', sqlite.JSON(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('acknowledged', sa.BOOLEAN(), nullable=True),
    sa.Column('acknowledged_by', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('assigned_to', sa.VARCHAR(length=120), nullable=True),
    sa.Column('suggested_actions', sqlite.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
