"""add stock_tracking table

Revision ID: d0f592990ea3
Revises: bc2bb5912ecf
Create Date: 2025-09-09 10:17:38.125060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0f592990ea3'
down_revision = 'bc2bb5912ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_tracking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_name', sa.String(length=128), nullable=False),
    sa.Column('date_in', sa.Date(), nullable=False),
    sa.Column('fruit_type', sa.String(length=64), nullable=False),
    sa.Column('quantity_in', sa.Float(), nullable=False),
    sa.Column('amount_per_kg', sa.Float(), nullable=False),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('other_charges', sa.Float(), nullable=True),
    sa.Column('date_out', sa.Date(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('gradient_used', sa.String(length=128), nullable=True),
    sa.Column('gradient_amount_used', sa.Float(), nullable=True),
    sa.Column('gradient_cost_per_unit', sa.Float(), nullable=True),
    sa.Column('total_gradient_cost', sa.Float(), nullable=True),
    sa.Column('quantity_out', sa.Float(), nullable=True),
    sa.Column('spoilage', sa.Float(), nullable=True),
    sa.Column('total_stock_cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchase')
    op.drop_table('assignments')
    op.drop_table('gradients')
    op.drop_table('inventory')
    op.drop_table('other_expenses')
    op.drop_table('driver_expenses')
    op.drop_table('salaries')
    op.drop_table('message')
    op.drop_table('sale')
    op.drop_table('stock_movement')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=True),
    sa.Column('role', sa.VARCHAR(length=11), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('salary', sa.FLOAT(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('stock_movement',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('inventory_id', sa.INTEGER(), nullable=False),
    sa.Column('movement_type', sa.VARCHAR(length=10), nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('remaining_stock', sa.VARCHAR(length=50), nullable=True),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('added_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('selling_price', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('assignment', sa.VARCHAR(length=100), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('revenue', sa.FLOAT(), nullable=False),
    sa.Column('sale_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('recipient_role', sa.VARCHAR(length=11), nullable=True),
    sa.Column('recipient_id', sa.INTEGER(), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salaries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.Column('is_paid', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('driver_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('driver_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=80), nullable=False),
    sa.Column('type', sa.VARCHAR(length=80), nullable=True),
    sa.Column('description', sa.VARCHAR(length=256), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('other_expenses',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('expense_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('location', sa.VARCHAR(length=100), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('added_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('purchase_price', sa.FLOAT(), nullable=True),
    sa.Column('purchase_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['added_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gradients',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('application_date', sa.DATE(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('gradient_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('notes', sa.VARCHAR(length=255), nullable=True),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=True),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
    sa.Column('purpose', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assignments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('seller_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fruit_type', sa.VARCHAR(length=80), nullable=False),
    sa.Column('assignment_id', sa.VARCHAR(length=80), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('purchaser_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('quantity', sa.VARCHAR(length=50), nullable=False),
    sa.Column('unit', sa.VARCHAR(length=20), nullable=False),
    sa.Column('buyer_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('cost', sa.FLOAT(), nullable=False),
    sa.Column('purchase_date', sa.DATE(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['purchaser_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('stock_tracking')
    # ### end Alembic commands ###
