"""add amount_per_kg to purchase

Revision ID: df96c6c8ab11
Revises: e6c19f3012d6
Create Date: 2025-09-09 15:39:47.303222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df96c6c8ab11'
down_revision = 'e6c19f3012d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('purchase', sa.Column('amount_per_kg', sa.Float(), nullable=False, server_default='0'))
    pass  # Column already present in model, skip adding
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('purchase', 'amount_per_kg')
    pass  # Column already present in model, skip dropping
    # ### end Alembic commands ###
