"""drop sale table

Revision ID: drop_sale_table
Revises: 7975c8bf8683
Create Date: 2024-10-01 12:00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'drop_sale_table'
down_revision = '7975c8bf8683'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sale')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('seller_fruit_id', sa.INTEGER(), nullable=True),
    sa.Column('assignment', sa.String(length=100), nullable=True),
    sa.Column('assignment_id', sa.INTEGER(), nullable=True),
    sa.Column('fruit_type', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=False),
    sa.Column('revenue', sa.Float(), nullable=False),
    sa.Column('sale_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['seller_fruit_id'], ['seller_fruits.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
