"""Add application_date, name, description to Gradient

Revision ID: ed2abc14753a
Revises: 0f3ea6866bae
Create Date: 2025-08-10 20:53:27.004145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed2abc14753a'
down_revision = '0f3ea6866bae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gradients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gradient')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gradient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('gradient_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('application_date', sa.DATE(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.Column('applied_by', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['applied_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('gradients')
    # ### end Alembic commands ###
