"""Add fields to gradients table and fix assignment FK

Revision ID: f9db22580929
Revises: ed2abc14753a
Create Date: 2025-08-14 17:49:18.904377

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9db22580929'
down_revision = 'ed2abc14753a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_id', sa.Integer(), nullable=False),
    sa.Column('seller_email', sa.String(length=120), nullable=False),
    sa.Column('fruit_type', sa.String(length=80), nullable=False),
    sa.Column('assignment_id', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assignment')
    with op.batch_alter_table('gradients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fruit_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('gradient_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('purpose', sa.String(length=100), nullable=True))

    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sale_assignment_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'assignments', ['assignment_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_sale_assignment_id', 'assignment', ['assignment_id'], ['id'])

    with op.batch_alter_table('gradients', schema=None) as batch_op:
        batch_op.drop_column('purpose')
        batch_op.drop_column('unit')
        batch_op.drop_column('quantity')
        batch_op.drop_column('notes')
        batch_op.drop_column('gradient_type')
        batch_op.drop_column('fruit_type')

    op.create_table('assignment',
    sa.Column('id', sa.VARCHAR(length=100), nullable=False),
    sa.Column('seller_id', sa.INTEGER(), nullable=False),
    sa.Column('seller_email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('fruit_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('assignments')
    # ### end Alembic commands ###
