"""enhance driver expenses with car details

Revision ID: fed639a7a380
Revises: 34c2c61fe0ec
Create Date: 2025-09-21 09:56:57.685729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed639a7a380'
down_revision = '34c2c61fe0ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver_expenses', sa.Column('car_number_plate', sa.String(length=20), nullable=True))
    op.add_column('driver_expenses', sa.Column('car_name', sa.String(length=100), nullable=True))
    op.add_column('driver_expenses', sa.Column('stock_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driver_expenses', 'stock_name')
    op.drop_column('driver_expenses', 'car_name')
    op.drop_column('driver_expenses', 'car_number_plate')
    # ### end Alembic commands ###
